version: '2.1'

services:
  docs:
    image: ghcr.io/wombatcyberlabs/lab-content-pivotlab-docs:main
    restart: always
    hostname: docs
    ports:
      - "80:80"
    networks:
      lab_net:
        ipv4_address: 10.13.37.10
  uptimechecker:
    image: ghcr.io/wombatcyberlabs/lab-utility-uptimechecker:main
    restart: always
    hostname: uptimechecker
    ports:
      - "8080:8080"
    volumes:
      - ./serviceconfig.json:/app/config.json:ro
    networks:
      lab_net:
        ipv4_address: 10.13.37.11
      ssrf_net:
        ipv4_address: 10.13.38.11
  dockovpn:
    image: alekslitvinenk/openvpn:v1.9.0-regen-dh
    restart: always
    hostname: vpn
    networks:
      lab_net:
        ipv4_address: 10.13.37.9
    ports:
      - "1194:1194/udp"
    cap_add:
      - NET_ADMIN
    environment:
      HOST_ADDR: '0.0.0.0'
    volumes:
      - ./openvpnserver.conf:/etc/openvpn/server.conf:ro
  vpnconfig:
    image: ghcr.io/wombatcyberlabs/lab-utility-vpnconfig:main
    restart: always
    hostname: vpnconfig
    depends_on:
      - dockovpn
    networks:
      lab_net:
        ipv4_address: 10.13.37.8
    ports: 
      - "8081:80"

  gogs:
    image: gogs/gogs:0.11.43
    restart: always
    ports:
      - "8091:3000"
    hostname: gogs
    networks:
      lab_net:
        ipv4_address: 10.13.37.21
      ssrf_net:
        ipv4_address: 10.13.38.21
    healthcheck:
      test: "curl -f http://localhost:3000/"
      interval: 10s
      timeout: 5s
      retries: 5
  gogsinit:
    image: ghcr.io/wombatcyberlabs/lab-content-pivotlab-gogsinit:main
    hostname: gogsinit
    networks:
      lab_net:
        ipv4_address: 10.13.37.22
    depends_on:
      gogs:
        condition: service_healthy
  ssrftarget:
    image: ghcr.io/wombatcyberlabs/lab-content-pivotlab-ssrftarget:main
    restart: always
    hostname: ssrftarget
    networks:
      ssrf_net:
        ipv4_address: 10.13.38.23
  sshserver:
    image: ghcr.io/wombatcyberlabs/lab-content-pivotlab-sshserver:main
    restart: always
    hostname: sshserver
    ports:
      - "8092:22"
    networks:
      lab_net:
        ipv4_address: 10.13.37.24
      ssh_net:
        ipv4_address: 10.13.39.24
  telnetserver:
    image: ghcr.io/wombatcyberlabs/lab-content-pivotlab-opentelnet:main
    restart: always
    hostname: telnetserver
    networks:
      ssh_net:
        ipv4_address: 10.13.39.146
    

networks:
  lab_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.13.37.0/24
  ssrf_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.13.38.0/24
  ssh_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.13.39.0/24
